export const dummyHospitals = [
  {
    id: 1,
    name: "Lagos University Teaching Hospital (LUTH)",
    lga: "Ikeja",
    address: "Idi-Araba, Mushin, Lagos",
    phone: "+234 802 345 6789",
    emergency: "0800 123 4567",
    aiMatch: 94,
    specialties: ["Cardiology", "Neurology", "Pediatrics", "Internal Medicine"],
    insurance: ["NHIS", "Hygeia", "AXA Mansard", "Leadway"],
    programs: [
      { name: "Annual Health Screening", availability: "Available" },
      { name: "Diabetes Prevention", availability: "Available" },
      { name: "Blood Pressure Monitoring", availability: "Limited" },
    ],
    resources: [
      { type: "blood", bloodType: "A+", quantity: 12 },
      { type: "blood", bloodType: "B+", quantity: 8 },
      { type: "blood", bloodType: "O+", quantity: 15 },
      { type: "icu", quantity: 4, total: 10 },
      { type: "antivenom", available: true },
    ],
    lastUpdated: Date.now() - 1000 * 60 * 5,
  },
  {
    id: 2,
    name: "Gbagada General Hospital",
    lga: "Kosofe",
    address: "Gbagada Phase 2, Lagos",
    phone: "+234 803 456 7890",
    emergency: "0800 234 5678",
    aiMatch: 87,
    specialties: ["General Practice", "Pediatrics", "Emergency Medicine"],
    insurance: ["NHIS", "Hygeia"],
    programs: [
      { name: "Vaccination Drive", availability: "Available" },
      { name: "Malaria Prevention", availability: "Available" },
      { name: "Maternal Health", availability: "Limited" },
    ],
    resources: [
      { type: "blood", bloodType: "A+", quantity: 3 },
      { type: "blood", bloodType: "O+", quantity: 2 },
      { type: "icu", quantity: 1, total: 8 },
      { type: "antivenom", available: false },
    ],
    lastUpdated: Date.now() - 1000 * 60 * 15,
  },
  {
    id: 3,
    name: "Ikeja Medical Centre",
    lga: "Ikeja",
    address: "21 Medical Road, Ikeja, Lagos",
    phone: "+234 804 567 8901",
    emergency: "0800 345 6789",
    aiMatch: 91,
    specialties: ["Internal Medicine", "Cardiology", "Orthopedics"],
    insurance: ["NHIS", "AXA Mansard", "Leadway"],
    programs: [
      { name: "Heart Health Screening", availability: "Available" },
      { name: "Wellness Workshop", availability: "Available" },
      { name: "Senior Care Program", availability: "Available" },
    ],
    resources: [
      { type: "blood", bloodType: "A+", quantity: 8 },
      { type: "blood", bloodType: "O+", quantity: 10 },
      { type: "icu", quantity: 3, total: 6 },
      { type: "antivenom", available: true },
    ],
    lastUpdated: Date.now() - 1000 * 60 * 30,
  },
  {
    id: 4,
    name: "Federal Medical Centre",
    lga: "Ebute Metta",
    address: "22/24 Harvey Road, Ebute Metta, Lagos",
    phone: "+234 805 678 9012",
    emergency: "0800 456 7890",
    aiMatch: 76,
    specialties: ["General Practice", "Pediatrics", "Obstetrics"],
    insurance: ["NHIS"],
    programs: [
      { name: "Child Immunization", availability: "Available" },
      { name: "Prenatal Care", availability: "Limited" },
      { name: "Family Planning", availability: "Available" },
    ],
    resources: [
      { type: "blood", bloodType: "A+", quantity: 0 },
      { type: "blood", bloodType: "O+", quantity: 0 },
      { type: "icu", quantity: 0, total: 5 },
      { type: "antivenom", available: false },
    ],
    lastUpdated: Date.now() - 1000 * 60 * 45,
  },
  {
    id: 5,
    name: "Surulere General Hospital",
    lga: "Surulere",
    address: "32 Bode Thomas Street, Surulere, Lagos",
    phone: "+234 806 789 0123",
    emergency: "0800 567 8901",
    aiMatch: 89,
    specialties: ["Internal Medicine", "Surgery", "Pediatrics"],
    insurance: ["NHIS", "Hygeia", "Leadway"],
    programs: [
      { name: "Diabetes Management", availability: "Available" },
      { name: "Nutrition Counseling", availability: "Available" },
      { name: "Exercise Programs", availability: "Limited" },
    ],
    resources: [
      { type: "blood", bloodType: "A+", quantity: 6 },
      { type: "blood", bloodType: "O+", quantity: 4 },
      { type: "icu", quantity: 2, total: 7 },
      { type: "antivenom", available: true },
    ],
    lastUpdated: Date.now() - 1000 * 60 * 60,
  },
];
